### ISSUE TITLE
Considering how to handle web page titles localized by region - fewer results for same site in another country

### ISSUE THREAD

**Issue by frizensami** [UseCrowdWise/crowdwise#131]
Original title: Visiting lichess.org from Spain returns only irrelevant spanish results (user report) 

From reddit comment: https://www.reddit.com/r/SideProject/comments/v5e6rt/comment/ibb8tzs/?utm_source=share&utm_medium=web2x&context=3 

No issue with access from Singapore:
![image](https://user-images.githubusercontent.com/5507069/172088609-f3cc8c25-16e3-4e39-a115-c724ba380820.png)

**Comment by frizensami** [comment]
https://imgur.com/a/dVjhUaW

**Comment by yewsiang** [comment]
No fix for now because might be non-trivial
