### ISSUE TITLE
Sort Top Comments for Hacker News by most replies

### ISSUE THREAD

**Issue by frizensami** [UseCrowdWise/crowdwise#154]

**Comment by yewsiang** [comment]
Is Exact URL match turned on? If that's the case then those results will be at the top first

**Comment by frizensami** [comment]
I should have been more descriptive. Basically, the top comments on HN/reddit don't match with the top comments being shown by Crowdwise. Take GitHub.com comment results for the first match:

![image](https://user-images.githubusercontent.com/5507069/173734236-23f64e49-279d-4c91-a79f-ecddc02f7cad.png)

Vs what the actual top comments are on HN
![image](https://user-images.githubusercontent.com/5507069/173734255-18290f47-886a-48ea-a7ce-82cb45a67ca5.png)

**Comment by frizensami** [comment]
More specifically, it works on reddit (because i explicitly sorted by top comments first) but not for hacker news. I need to fix that.
