### ISSUE TITLE
Hacker News and Reddit comments show different bottom bar icons (no. of likes vs no. of comments?)

### ISSUE THREAD

**Issue by frizensami** [UseCrowdWise/crowdwise#156]

**Comment by yewsiang** [comment]
Oh this is because HN mostly don't have points

**Comment by frizensami** [comment]
Ah, maybe we should remove that likes/comments bottom bar or something for standardization. Or let me see what the API can return us.

**Comment by yewsiang** [comment]
It is fine to show different values
