### ISSUE TITLE
List of URLs that returns unrelated results

### ISSUE THREAD

**Issue by yewsiang** [UseCrowdWise/crowdwise#30]
Link: https://mui.com/

![Screenshot 2022-02-23 at 10 42 31 AM](https://user-images.githubusercontent.com/14248879/155253444-c559acbf-9244-42b8-95c0-1f01bffe7612.png)

**Comment by frizensami** [comment]
Interesting. The HN API is somehow accepting mui.com for all mi.com links, and reddit also is not doing an exact search. I can't find a way to get it to an exact search.

**Possible solution**: we may have to 
1. filter the results _after_ we receive them to only include exact matches
2. ask for more pages of results from HN/reddit

**Comment by frizensami** [comment]
https://en.wikipedia.org/wiki/Tenkasi 

HN returns https://en.wikipedia.org/wiki/Tenkasi (Tensile strength).

Lol

**Comment by frizensami** [comment]
usefriz.com gets links for usefyi.com from HN API

**Comment by frizensami** [comment]
This exact issue is no longer relevant because of our ML filtering
